### ISSUE TITLE
Keycard doors

### ISSUE THREAD

**Issue by lilianluong** [JasonLin43212/Heist#62]
- [x] keycard item with unlimited uses
 - [x] KeycardDoor prefab
 - [x] keycards can open a list of doors
 - [x] when keycard is used near a matching door, the door is toggled

**Comment by andi6558** [comment]
Looks pretty good, I love that a) when the keycard is around the door the edge of the door turns black and b) the button turns darker when stepped on. However, there are somethings I would like to change, in the order of importance:
- [ ] It would be better if the keycard can only be used once, since in my mind it is an incentive to get the player go somewhere, multiple times in a level, so in that case a keycard should dissappear after interacting with the door. Along with this change, maybe the keycard door could be non-interactable after being toggled the first time, just to make sure the players don't do dumb things.
- [ ] (Needs further discussion) It would be more smooth if players could just pick up items by walking on them. There is not much reason why not to pick up things, and players could easily pick up their old item by walking onto the old one again. This fixes the problem that playertesters are very confused about the two keys involved in item interaction.
- [ ] There would be this UnassignedReferenceException if I make a new scene. Saying the variable dialogueUI of CutsceneController has not been assigned.
- [ ] Doors, even without checking "toggle permanently," can only be opened once, closed once, then not interactable anymore. This bug seems to apply to both the keycard door and button door. Though I am unlikely to use doors that are not toggled permanently, it would be better if that is fixed.
- [ ] A small ui change could be not displaying the radius of the keycard. The range of the keycard is not very important.

I also added a sprite to the keycard. All of the things mentioned above are tested in the scene dev/KeyCardTest

Great work!
